version: '3.8'

services:
  app:
    container_name: mh-app-service
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=MHAPI
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    container_name: mh-web-service
    image: nginx:alpine
    ports:
      - '1061:80'
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql_data:
