version: '3.8'
name: mhapi
services:
  fpm:
    container_name: mh-app-service
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ..:/var/www/html
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=mhapi
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mh-db-service
    image: mysql:8.0
    ports:
      - '3308:3306'
    env_file:
        - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      interval: 10s
      retries: 5
      timeout: 5s

  nginx:
    container_name: mh-web-service
    image: nginx:alpine
    ports:
      - '1061:80'
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm

volumes:
  mysql_data:
